apiVersion: apps/v1
kind: Deployment
metadata:
  name: "react-ui"
  labels:
    app: react-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "react-ui"
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
        - name: "react-ui"
          image: "deekshithsn/ui"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          # Add Liveness Probe
          livenessProbe:
            httpGet:
              path: /health   # Change this path to your application's health endpoint
              port: 8080      # Change this port to the port your application listens on
            initialDelaySeconds: 30 # Wait this long before starting the probe
            periodSeconds: 10       # Check every 10 seconds

          # Add Readiness Probe
          readinessProbe:
            httpGet:
              path: /ready    # Change this path to your application's readiness endpoint
              port: 8080      # Change this port to the port your application listens on
            initialDelaySeconds: 10 # Wait this long before starting the probe
            periodSeconds: 5        # Check every 5 seconds

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "react-ui"
  name: "ui"
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: "react-ui"
  type: "NodePort"

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: react-ui-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-ui
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Set your target CPU utilization percentage here
